template.yaml
- Ensured the session table name is created based on the Env Var defined in the template
- For dev, the session table name also includes the AWS Stack Name
- Added an output to expose the name of the table actually deployed
- [F2F-476](https://govukverify.atlassian.net/browse/F2F-476)
[F2F-476]: https://govukverify.atlassian.net/browse/F2F-476?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-476] Table name set with stack name in dev

CODEOWNERS
Removed old root folder CODEOWNERS file which was not  in use
- [F2F-445](https://govukverify.atlassian.net/browse/F2F-445)
[F2F-445]: https://govukverify.atlassian.net/browse/F2F-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-445: Removed old root folder CODEOWNERS file

src/assets/scss/application.scss, src/locales/en/fields.yml, src/views/f2f/findBranch.html
https://govukverify.atlassian.net/browse/F2F-589
Updated /findBranch page to use label for form field.
Page previously failed WCAG 2.1 accessibility requirements for go-live - specifically a lacking label for the input form (this was present visually, but not configured appropriately).
Attached evidence of axe tests passing with 0 critical/serious issues and label visible in HTML code for page:
=> [F2F-589] - F2F UI - Critical/Serious Accessibility Violations

src/locales/en/fields.yml, src/views/f2f/eeaIdentityCardCountrySelector.html, src/views/f2f/euDrivingLicenceCountrySelector.html, src/views/f2f/nonUkPassportCountrySelector.html
https://govukverify.atlassian.net/browse/F2F-677
Added label to country select drop-down where it is present (EU DL, EU ID, Non-UK Passport)
Updated designs: https://www.figma.com/file/tK7chtvE4bSaWSmBU7zcLV/F2F-Flow---Screen-Iterations?type=design&node-id=6616-289062&t=l9C5diTPMMbprlqX-4
A label is required as to meet accessibility requirements, screenshot attached:
=> [F2F-677] - F2F UI - Country Selector Screens Critical/Serious Accessibility Violations

src/app/f2f/controllers/checkDetails.js, src/app/f2f/controllers/checkDetails.test.js, src/app/f2f/controllers/results.js
- Sending the name of the post office to the /documentSelection endpoint
- Trimming off the postcode from the post office address, as the post office is it's own field and does not need to be repeated
Tweaks requested out of beta testing
Request body being sent to  /documentSelection
- [F2F-909](https://govukverify.atlassian.net/browse/F2F-909)
- API changes have been made in [backend PR](https://github.com/alphagov/di-ipv-cri-f2f-api/pull/147) 
[F2F-909]: https://govukverify.atlassian.net/browse/F2F-909?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-909] updates post office details sent to document selection endpoint

src/app/f2f/fields.js, test/mocks/mappings/documentSelection.json
More changes for radio button reveal text needed on DL and EEA card screens
- [F2F-911](https://govukverify.atlassian.net/browse/F2F-911)
**Before**
**After**
[F2F-911]: https://govukverify.atlassian.net/browse/F2F-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-911]: Copy changes on EU DL, UK DL and EEA card

.gitignore, Dockerfile.test, package.json, run-tests-locally.sh, run-tests.sh, template.yaml, test/utils/multiReportGenerator.js, yarn.lock
- Added test container shell script to run test in codepipeline and locally.
- Update template to include an output for F2F IPV stub URL.
- Docker.test file for the test container image.
- multiple-cucumber-html-reporter node module for html reports.
Test container image required for running tests in the pipeline.
- [F2F-968](https://govukverify.atlassian.net/browse/F2F-968)
[F2F-968]: https://govukverify.atlassian.net/browse/F2F-968?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Added test container script with reports

template.yaml
- Create a metric filter for FE APIGW & ECS if log message contains level is FATAL or message has Exception Unhandled
- Create a cloud watch alarm if the log group finds the metric filter
- Stack notification is sent if the alarm is triggered
- tested manually writing a Fatal error log on the log messages
- [F2F-1017](https://govukverify.atlassian.net/browse/F2F-1017)
[F2F-1017]: https://govukverify.atlassian.net/browse/F2F-1017?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1017: Create alerting for fatal errors in FE and BE

test/browser/support/setup.js
The global timeout for steps in the cucumber tests is increased from 5s to 10s.
Tests were timing out in the CodeBuild containers, whereas they passed on dev machines and on GHA.
- [F2F-1131](https://govukverify.atlassian.net/browse/F2F-1131)
[F2F-1131]: https://govukverify.atlassian.net/browse/F2F-1131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> F2F-1131 increase cucumber timeout

test/browser/pages/ukPassportDetailsPageInvalidPast.js
Extended the expiryDate calculation from 18months & 2 days to 18months and 5 days to account for leap years across the 18month period
https://govukverify.atlassian.net/browse/F2F-1155
=> [F2F-1155] - Update expiryDate in FE test

Dockerfile.test
Updates dockerfile.test to use ubuntu
amazonlinux is incompatible with node 18
Dev deploy working 
- [F2F-891](https://govukverify.atlassian.net/browse/F2F-891)
[F2F-891]: https://govukverify.atlassian.net/browse/F2F-891?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [F2F-891] Updates dockerfile.test to use ubuntu

src/app/f2f/controllers/abort.js
Currently the redirect URL appears like so id=f2f?error%3Daccess_denied&
This change adds decodeURIComponent to decode the encoded URL from Abort endpoint
=> [KIWI-1245] Decode the redirect URL on Abort

template.yaml
Add F2FBackendURL export for use in TestHarness to fix Test stage
=> Add F2FBackendURL export

src/app/f2f/fields.js, test/browser/pages/brpDetailsPageInvalidFuture.js
Changes expiry date limit for BRP
Because there are BRPs in circulation with expiry dates up to and including 31/12/2032
- [F2F-1202](https://govukverify.atlassian.net/browse/F2F-1202)
Before
After
=> [KIWI-1202] Changes expiry date limit for BRP

.github/CODEOWNERS, .github/pull_request_template.md
- Add the CODEOWNERS for new govuk-one-login github F2F Front
- [KIWI-1321](https://govukverify.atlassian.net/browse/KIWI-1321)
[KIWI-1321]: https://govukverify.atlassian.net/browse/KIWI-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1321: Github Migrations - Post cleanup for F2F Front

src/locales/en/default.yml, src/locales/en/pages.errors.yml
Any references to “[GOV.UK](http://gov.uk/) account” should be replaced with “[GOV.UK](http://gov.uk/) One Login”
https://govukverify.atlassian.net/browse/KIWI-1171
=> [KIWI-1171] - Update Copy to Fix Page Title Errors

src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/en/default.yml, src/locales/en/pages.errors.yml, src/views/errors/error.html, src/views/f2f/error.html
Updates support link
There is a new contact centre URL
- [KIWI-1152](https://govukverify.atlassian.net/browse/KIWI-1152)
[KIWI-1152]: https://govukverify.atlassian.net/browse/KIWI-1152?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1152] Updates support link

package.json, run-tests-locally.sh, test/browser/support/TestHarness.js
Adds required `customCredentialsProvider` for sigv4
To fix end to end tests
=> Gets sigv4 working

.secrets.baseline, template.yaml
AWS Security compliance to add security rule for load balance
Enabled alb-http-drop-invalid-header-enabled set to true
Security Compliance recommendation
- [KIWI-1486](https://govukverify.atlassian.net/browse/KIWI-1486)
[KIWI-1486]: https://govukverify.atlassian.net/browse/KIWI-1486?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1486: Implement security rule for ALB

src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/f2f/choose-photo-id-post-office.html
Minor revisions to BRP subtext and the page instructions, with Welsh translations added. Removed "I want to prove my identity another way" link.
To make the instructions clearer to users in English and Welsh
- [KIWI-1532](https://govukverify.atlassian.net/browse/KIWI-1532)
[KIWI-1532]: https://govukverify.atlassian.net/browse/KIWI-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1532] - F2F | FE | Subtext and Copy Changes to Document Selection Screen

package.json, src/app.js, src/lib/helmet.js, yarn.lock
- common-express is now [published as an npm package](https://www.npmjs.com/package/@govuk-one-login/di-ipv-cri-common-express) in the govuk-one-login organisation
- this PR updates to the latest version on npm
- [KIWI-1484](https://govukverify.atlassian.net/browse/KIWI-1484)
[KIWI-1484]: https://govukverify.atlassian.net/browse/KIWI-1484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Update to @govuk-one-login/di-ipv-cri-common-express

src/locales/en/fields.yml
Added empty hint to translation file
To fix defect where we are showing untranslated string
- [KIWI-1593](https://govukverify.atlassian.net/browse/KIWI-1593)
[KIWI-1593]: https://govukverify.atlassian.net/browse/KIWI-1593?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1593: Fix copy issue

package.json, src/app.js, src/lib/helmet.js, yarn.lock
Upgrade common-express to v5.0.0
Regression testing: https://govukverify.atlassian.net/browse/KIWI-1615?focusedCommentId=125066
=> [Kiwi 1615] - Upgrade common-express to v5.0.0

src/app/f2f/controllers/checkDetails.js, src/app/f2f/utils.js, src/app/f2f/utils.test.js
Changed formatDate function to format the user's chosen ID expiry date in the check answers page as DD Month YYYY, where month is either in English or Welsh depending on the language cookie.
To reflect the outcome of the WCAG accessibility audit.
- [KIWI-1637](https://govukverify.atlassian.net/browse/KIWI-1637)
- [ /] Added screenshots to show the implementation is working
[KIWI-1637]: https://govukverify.atlassian.net/browse/KIWI-1637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1637]- F2F | FE | Accessibility Audit | Format dates on CYA

check-logs.sh, package.json, run-tests.sh, test/browser/support/shared_claim.json
Adding PII check-logs script to scan for PII data used for automated tests
Note that only shared_claim.json file is used for automated tests and other test data json files are used for staging tests.
Catch PII in dev before deployment
- [KIWI-1526](https://govukverify.atlassian.net/browse/KIWI-1526)
Evidence of tests passing when no PII data is found for ref:
[KIWI-1526]: https://govukverify.atlassian.net/browse/KIWI-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1526] Adding PII check-logs script for automated tests

src/app/f2f/fields.js, src/app/f2f/steps.js, src/lib/config.js, src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/components/countrySummaryListThinFileNoExpiry.njk, src/views/components/countryThinFileSummaryList.njk, src/views/components/ukPassportThinFileSummaryList.njk, src/views/f2f/do-you-have-UK-passport.html
Changed copy and removed non-UK biometric option from radio buttons on thin file selection page.
[KIWI-1714](https://govukverify.atlassian.net/browse/KIWI-1714)
[KIWI-1714]: https://govukverify.atlassian.net/browse/KIWI-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1714] - Update thin file user page

.secrets.baseline, template.yaml
Alarm description on the front end does not hold the support manual url. Add the support manual url to the alarm description and point to the FE Metrics page. 
- Add Support Manual URL and point to the FE Metrics pages https://govukverify.atlassian.net/wiki/spaces/FTFCRI/pages/3623649281/F2F+FE+Metrics+Alerts
- Add Support manual description to Alarm descriptions
To include the support url on the alarms
- [KIWI-1603](https://govukverify.atlassian.net/browse/KIWI-1603)
[KIWI-1603]: https://govukverify.atlassian.net/browse/KIWI-1603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1603: Add Support Manual URL pointing to FE Metrics Page

.secrets.baseline, template.yaml
Alarms are created on dev for every custom stack created on the dev account. 
In order to optimise the stack, alarm is set to off by default 
Change the flag to deploy on dev set to false.
Added the condition on metric filter and alarms
Too many alarms created when a new custom is created.
Alarms are created on dev for every custom stack created on the dev account. 
In order to optimise the stack, alarm is set to off by default 
Change the flag to deploy on dev set to false.
Added the condition on metric filter and alarms
Modified the concurrency alarms flag.
Too many alarms created when a new custom is created.
- [KIWI-1718](https://govukverify.atlassian.net/browse/KIWI-1718)
- [IPS-678](https://govukverify.atlassian.net/browse/IPS-678)
[KIWI-1718]: …
=> KIWI-1718: Set alarms to off default in dev

src/assets/scss/application.scss
Changed width of error summary component
To align with GOV UK design system
- [KIWI-1798](https://govukverify.atlassian.net/browse/KIWI-1798)
[KIWI-1798]: https://govukverify.atlassian.net/browse/KIWI-1798?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1798] - Remove the width limit on the error summary component

test/browser/features/BrowserBasedTests/UnhappyPath/CMAChangeButton/F2FCheckAnswersIDSelectionChange.feature
Update logic for Change PhotoId - UnHappy Path test
- Uncomment test in F2FCheckAnswersIDSelectionChange.feature
- Add BDD step to fill out expiry date information for initial photoId choice (Non UK Passport) 
- Add BDD step to fill out expiry date information for second photoId choice (EU Drivers Licence) 
Test feature file has been commented out for a while, test logic needed refactoring to get tests to pass. 
- [KIWI-1814](https://govukverify.atlassian.net/browse/KIWI-1814)
[KIWI-1814]: https://govukverify.atlassian.net/browse/KIWI-1814?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1814- Update logic for change photoId journey

package.json, test/browser/features/BrowserBasedTests/UnhappyPath/POLookup/F2FPostOfficeIncompleteData.feature, test/browser/pages/findBranch.js, test/browser/pages/index.js, test/browser/pages/ipvError.js, test/browser/step_definitions/F2FDocumentSelectionUKPassport.step.js, test/browser/step_definitions/errors.js
- New test added to check we're directed to IPV Core error page when a user enters a postCode that returns incomplete data from the Post Office API (postCode suffix = MNE) 
- New page object added to store IPV Core error validation logic 
KIWI-1756 dev complete to improve the user journey when the PO API returns incomplete data for any reason
- [KIWI-1756](https://govukverify.atlassian.net/browse/KIWI-1756)
[KIWI-1756]: https://govukverify.atlassian.net/browse/KIWI-1756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi 1726 qa

.secrets.baseline, template.yaml
- Deploy Cloudfront origin on all F2F accounts
- Previously, the cloudfront origin been deployed on dev environment
- Disabled the Web ACL association on the dev environment
- Changed include the web acl association applied on all environments
- Add DNS record on all F2F accounts
- [IPS-688](https://govukverify.atlassian.net/browse/IPS-688)
[IPS-688]: https://govukverify.atlassian.net/browse/IPS-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-688: Deploy Cloudfront Origin records on all F2F environments

test/browser/features/BrowserBasedTests/HappyPath/E2E/F2FEndToEnd.feature, test/browser/pages/photoIdSelectionPage.js, test/browser/step_definitions/F2FBackendValidation.step.js, test/browser/step_definitions/F2FLandingPage.step.js, test/browser/support/F2F_CRI_SESSION_ABORTED_SCHEMA.json, test/browser/support/F2F_CRI_START_SCHEMA.json, test/browser/support/TestHarness.js
Add E2E test to validate F2F Abort logic and validate to following:
- authSessionState = F2F_CRI_SESSION_ABORTED
- F2F_CRI_SESSION_ABORTED matched expected Schema
Increase scope of E2E testing + support E2E testing of CloudFront changes.
- [KIWI-1863](https://govukverify.atlassian.net/browse/KIWI-1863)
[KIWI-1863]: https://govukverify.atlassian.net/browse/KIWI-1863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1863 - Abort Logic E2E Tests with DB Validation

test/browser/support/F2F_CRI_SESSION_ABORTED_SCHEMA.json, test/browser/support/F2F_CRI_START_SCHEMA.json, test/browser/support/F2F_YOTI_START_00_SCHEMA.json, test/browser/support/F2F_YOTI_START_01_SCHEMA.json, test/browser/support/F2F_YOTI_START_02_SCHEMA.json, test/browser/support/F2F_YOTI_START_03_SCHEMA.json, test/browser/support/F2F_YOTI_START_04_SCHEMA.json, test/browser/support/F2F_YOTI_START_05_SCHEMA.json
Update following TxMA JSON Schema to check for `restricted.device_information` field
- F2F_YOTI_START_XX_SCHEMA.json
- F2F_CRI_SESSION_ABORTED_SCHEMA.json
- F2F_CRI_START_SCHEMA.json
Support testing of CloudFront changes
- [KIWI-1868](https://govukverify.atlassian.net/browse/KIWI-1868)
[KIWI-1868]: https://govukverify.atlassian.net/browse/KIWI-1868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1868 - Cloudfront Header Updates

.github/workflows/pre-merge-checks.yml, package.json, yarn.lock
Bump `@govuk-one-login/frontend-analytics` to v2.0.1
Request from FEC to upgrade due to a new release they’ve made to fix a bug they discovered
- [KIWI-1912](https://govukverify.atlassian.net/browse/KIWI-1912)
[KIWI-1912]: https://govukverify.atlassian.net/browse/KIWI-1912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Kiwi | FE | Upgrade to frontend-analytics version 2.0.1

src/app/f2f/controllers/checkDetails.js, src/app/f2f/controllers/checkDetails.test.js
pdf_preference property in front end payload sent to DocumentSelection lambda hardcoded to "EMAIL_ONLY"
To avoid breaking the BE as pdfPreference is subject to a check which throws an error if failed
=> [KIWI-1919] - Hardcode PDF Preference in FE payload for DocumentSelection lambda

src/app/f2f/controllers/landingPage.js
Fetching the feature flag from sessionConfig endpoint and storing it in the FE session store.
Printed Customer Letter feature requirement. Need to check this flag before the PCL related screens are displayed to the User.
- [KIWI-1903](https://govukverify.atlassian.net/browse/KIWI-1903)
Evidence of store saving this flag. For testing purpose only i had to console log out the value;
[KIWI-1903]: https://govukverify.atlassian.net/browse/KIWI-1903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-1903]Fetching the feature flag from sessionConfig endpoint and storing it in the FE session store.

src/app/f2f/controllers/checkDetails.js, src/app/f2f/controllers/checkDetails.test.js, src/app/f2f/controllers/landingPage.js, src/app/f2f/fields.js, src/app/f2f/steps.js, src/assets/scss/application.scss, src/lib/config.js, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/f2f/post-office-customer-letter.html
New screen to capture user PDF preference
So that users that want a instructions in the form of a posted letter in addition to email can make a request for one
- [KIWI-979](https://govukverify.atlassian.net/browse/KIWI-979)
[KIWI-979]: https://govukverify.atlassian.net/browse/KIWI-979?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-979] - F2F | PCL | FE | Create new screen for capturing customer PCL preference

test/browser/support/F2F_CRI_SESSION_ABORTED_SCHEMA.json
Add check for govuk_signin_journey_id in E2E test validating F2F_CRI_SESSION_ABORTED TxMA Event
Missing govuk_signin_journey_id field added to F2F_CRI_SESSION_ABORTED TxMA event.
- [KIWI-1947](https://govukverify.atlassian.net/browse/KIWI-1947)
[KIWI-1947]: https://govukverify.atlassian.net/browse/KIWI-1947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-1947 TxMA JSON Schema Update

template.yaml
This the second step of canary deployment on Stage 2 on frontend. After deploying all the additional stacks for the canary deployment, the load balancer and network configuration and task definition need to switched to the canary stack.
- Stage 2 of Canary deployment on the Frontend ECS 
- Shifted the Loadbalancers, network configuration and Task definitions Canary stack
- [IPS-560](https://govukverify.atlassian.net/browse/IPS-560)
[IPS-560]: https://govukverify.atlassian.net/browse/IPS-560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-560: Stage 2: Canary deployment on F2F - Step 2 Deployment

src/locales/en/fields.yml
Added missing hint text for radio buttons on printed customer letter screens
[KIWI-2104](https://govukverify.atlassian.net/browse/KIWI-2104)
[KIWI-2104]: https://govukverify.atlassian.net/browse/KIWI-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updated hint text for radio buttons

src/assets/scss/application.scss, src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/default.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/f2f/post-office-customer-letter-find-address.html
- Added correct label HTML tag to input label on `post-office-customer-letter-find-address` page
- Updated URL on landing page
- Minor copy updates
To ensure a consistent and accessible journey users
- [KIWI-2149](https://govukverify.atlassian.net/browse/KIWI-2149)
[KIWI-2149]: https://govukverify.atlassian.net/browse/KIWI-2149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2149] - Address UCD design review comments

src/app/f2f/controllers/checkDetails.js, src/app/f2f/utils.js, src/app/f2f/utils.test.js, src/presenters/addressPresenter.js, src/presenters/addressPresenter.test.js, test/browser/pages/landingPage.js, test/browser/step_definitions/details.js
Updated existing `toTitleCase` function to account for post codes and renamed to `titleCaseAddresses` + moved function location. Also removed unused `formatAddress` function and unused/duplicate unit tests.
To display the users chosen address in the correct format
- [KIWI-2155](https://govukverify.atlassian.net/browse/KIWI-2155)
[KIWI-2155]: https://govukverify.atlassian.net/browse/KIWI-2155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2155] - FE | Updating Postal address display in Check Details screen

src/assets/scss/application.scss, src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/cy/pages.yml, src/locales/en/default.yml, src/locales/en/fields.yml, src/locales/en/pages.yml, src/views/f2f/post-office-customer-letter-check-address.html, src/views/f2f/post-office-customer-letter-choose-address.html, src/views/f2f/post-office-customer-letter.html, test/browser/step_definitions/details.js
=> [KIWI-2156]Updating Error messaging and Title styling on PCL screens

src/app/f2f/controllers/root.js
Added check for sessionId in root controller axios call and log
Seeing a large number of failed Axios calls in the F2F FE, suspicion is that these are users with missing session Id
=> [KIWI-XXXX] - Added check for sessionId and additional log in root controller

template.yaml
Updating thresholds as array not a valid input for alarm threshold
=> KIWI-2020 - Fixing threshold for noTask and HighTask alarm

src/app.js
Add SIGTERM shutdown, and adjust keepalivetimeout duration to longer than loadbalancer timeout
To implement gracefull shutdown and avoid mismatch between loadbalancer timeout and keepalive.
=> KIWI-2016 - Adding Sigterm graceful close

src/app.js, src/lib/config.js
Added name to hmpo-logger.get() function to prevent use of sync API which blocks event loop
=> KIWI-2012 - Adding Package name to hmpo-logger

package.json, src/views/f2f/check-details.html, src/views/f2f/choose-photo-id-post-office.html, src/views/f2f/choose-post-office-prove-identity.html, src/views/f2f/do-you-have-UK-passport.html, src/views/f2f/eu-driving-licence-current-address.html, src/views/f2f/eu-driving-licence-expire.html, src/views/f2f/eu-driving-licence-expiry-date.html, src/views/f2f/find-post-office-prove-identity.html, src/views/f2f/national-identity-card-current-address.html, src/views/f2f/national-identity-card-expire.html, src/views/f2f/national-identity-card-expiry-date.html, src/views/f2f/non-uk-passport-expire.html, src/views/f2f/non-uk-passport-expiry-date.html, src/views/f2f/photo-id-expired.html, src/views/f2f/post-office-customer-letter-check-address.html, src/views/f2f/post-office-customer-letter-choose-address.html, src/views/f2f/post-office-customer-letter-find-address.html, src/views/f2f/post-office-customer-letter.html, src/views/f2f/prove-identity-post-office.html, src/views/f2f/select-country-eu-driving-licence.html, src/views/f2f/select-country-national-identity-card.html, src/views/f2f/select-country-non-uk-passport.html, src/views/f2f/uk-driving-licence-current-address.html, src/views/f2f/uk-driving-licence-expire.html, src/views/f2f/uk-passport-expire.html, yarn.lock
Upgraded frontend-analytics package version and added missing data attributes used for GA4 navigation tracking
To ensure service is up to date and capturing analytics data correctly
- [KIWI-2216](https://govukverify.atlassian.net/browse/KIWI-2216)
[KIWI-2216]: https://govukverify.atlassian.net/browse/KIWI-2216?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2216] Upgrade FE analytics from v 2.0.1 to 3.1.0

.secrets.baseline, template.yaml
Replaced existing ECS autoscaling policy with step scale-in and scale-out policies, with alarms
To meet requirement of ADR 140 and scale more effectively for our use cases in KIWI
https://github.com/govuk-one-login/architecture/blob/main/adr/0140-fargate-scaling.md
- [KIWI-2244](https://govukverify.atlassian.net/browse/KIWI-2244)
[KIWI-2244]: https://govukverify.atlassian.net/browse/KIWI-2244?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2244] - KIWI | CM | Aligning Auto-Scaling Policies with ADR 140

.secrets.baseline, template.yaml
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
- [IPS-1407](https://govukverify.atlassian.net/browse/IPS-1407)
[IPS-1407]: https://govukverify.atlassian.net/browse/IPS-1407?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-1407: Migrate WAF in F2F CRI to FMS

package.json, yarn.lock
Updated common-express package to latest version which includes fix for device intelligence feature toggle.
- [KIWI-2261](https://govukverify.atlassian.net/browse/KIWI-2261)
[KIWI-2261]: https://govukverify.atlassian.net/browse/KIWI-2261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2261 - Bump common-express version

template.yaml
Disabled Device Intelligence in Staging env by setting the value of `DEVICEINTELLIGENCEENABLED` env var in CF template to `false`
To unblock IPV core pipelines as referenced [here]([here](https://gds.slack.com/archives/C05HE9FL65S/p1747759982973109?thread_ts=1747756522.823159&cid=C05HE9FL65S))
- [KIWI-2323](https://govukverify.atlassian.net/browse/KIWI-2323)
[KIWI-2323]: https://govukverify.atlassian.net/browse/KIWI-2323?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KIWI-2303 - DI | Turn off Device Intelligence in Staging

.secrets.baseline, src/lib/config.js, template.yaml
Set device intelligence cookie domain to account.gov.uk across all envs
To address issue with header size stemming from environment specific domain names
- [KIWI-2318](https://govukverify.atlassian.net/browse/KIWI-2318)
[KIWI-2318]: https://govukverify.atlassian.net/browse/KIWI-2318?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2318] - DI | Set Cookie domain for all environments

template.yaml
Turned on Device Intelligence in staging, integration and production
To enable the program to collect collection and analysis of data from end user devices and satisfy HMRC Day2 Must Have requirements
- [KIWI-2251](https://govukverify.atlassian.net/browse/KIWI-2251)
[KIWI-2251]: https://govukverify.atlassian.net/browse/KIWI-2251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2251] - | FE | Enable feature flag for Device Intelligence in INT and PROD

template.yaml
Set the Rebrand feature flag in Integration to true
To align with rebranding and allow for further E2E testing.
- [KIWI-2331](https://govukverify.atlassian.net/browse/KIWI-2331)
[KIWI-2331]: https://govukverify.atlassian.net/browse/KIWI-2331?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2331] -  F2F | FE | Enable the Rebrand feature flag in Integration

.github/dependabot.yml
Updated dependabot yaml to group aws-sdk, ignored arm64v8/node and node 24
To group aws-sdk related PRs together, and ignore node 24
- [KIWI-2423](https://govukverify.atlassian.net/browse/KIWI-2423)
[KIWI-2423]: https://govukverify.atlassian.net/browse/KIWI-2423?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [KIWI-2423] - Dependabot | Sprint 6 | Update yaml file 
