govuk-one-login/ipv-cri-f2f-front

- .github/workflows/post-merge-actions-build.yml
Added post merge package to build file
- [F2F-183](https://govukverify.atlassian.net/browse/F2F-183)
[F2F-183]: https://govukverify.atlassian.net/browse/F2F-183?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-183 Added post merge package to build file

- template.yaml
Updated the API Gateway ID to the new BE ID
> [F2F-15a] - Update template.yaml

- template.yaml
> [F2F-41]: correcting proxy url

- template.yaml
Added FE Custom Domain to communicate with BE
- [F2F-470](https://govukverify.atlassian.net/browse/F2F-470)
[F2F-470]: https://govukverify.atlassian.net/browse/F2F-470?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-470] FE Custom domain

- .github/workflows/checks.yml
Uncomment test
- [F2F-40](https://govukverify.atlassian.net/browse/F2F-40)
[F2F-40]: https://govukverify.atlassian.net/browse/F2F-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-40 Uncomment test

- .github/workflows/checks.yml
- package.json
- src/lib/settings.js
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FFindBranchValid.feature
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FSelectLocation.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/ChangeButton/F2FSelectionLocationChangePostcode.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FSelectLocationNoSelection.feature
- test/browser/pages/findBranch.js
- test/browser/pages/postOfficeLocations.js
- test/browser/step_definitions/F2FFindBranchValid.step.js
- [F2F-40](https://govukverify.atlassian.net/browse/F2F-40)
[F2F-40]: https://govukverify.atlassian.net/browse/F2F-40?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Removed unused vars

- template.yaml
Added CSLS integration to send logs to Splunk
- [F2F-485](https://govukverify.atlassian.net/browse/F2F-485)
[F2F-485]: https://govukverify.atlassian.net/browse/F2F-485?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-485 Added CSLS integration to send logs

- src/app/f2f/steps.js
- src/assets/scss/application.scss
- src/locales/en/pages.yml
- src/views/f2f/landingPage.html
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FFindBranchValid.feature
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FSelectLocation.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/ChangeButton/F2FSelectionLocationChangePostcode.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchEmpty.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchInvalid.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchPartial.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FSelectLocationNoSelection.feature
- test/browser/step_definitions/F2FLandingPage.step.js
- test/browser/step_definitions/F2FSelectLocationChangePostcode.step.js
- test/browser/step_definitions/details.js
- [F2F-398](https://govukverify.atlassian.net/browse/F2F-398)
[F2F-398]: https://govukverify.atlassian.net/browse/F2F-398?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2 f 398 - Migrate Landing Page from CIC to F2F

- src/app/f2f/controllers/photoIdSelection.js
- src/app/f2f/controllers/photoIdSelection.test.js
- src/app/f2f/fields.js
- src/app/f2f/steps.js
- src/assets/scss/application.scss
- src/lib/config.js
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/f2f/photoIdSelection.html
- test/browser/features/BrowserBasedTests/HappyPath/LandingPage/F2FLandingPage.feature
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FFindBranchValid.feature
- test/browser/features/BrowserBasedTests/HappyPath/PostOffice/F2FSelectLocation.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/BackButton/F2FDocumentSelectionGoBack.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/ChangeButton/F2FSelectionLocationChangePostcode.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchEmpty.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchInvalid.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FFindBranchPartial.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FSelectLocationNoSelection.feature
- test/browser/pages/index.js
- test/browser/pages/photoIdSelectionPage.js
- test/browser/step_definitions/F2FDocumentSelectionReturnToLP.js
- test/browser/step_definitions/F2FLandingPage.step.js
- yarn.lock
https://govukverify.atlassian.net/browse/F2F-400
- Added Document Selection screen to F2F from CIC. Also added browser/unit tests. 
- Note: Existing browser tests incorporating the old flow (Only PO location finder->results) have been commented out, can be added back in once expiry date screens are added so complete flow is accessible.
https://govukverify.atlassian.net/browse/F2F-422
- Removed unnecessary documents as described in ticket (Young Scotts Pass and Citizens Card)
**All files mentioned above are still present in CIC.**
> F2F-400/422

- template.yaml
Updating APIBaseUrl in FE Template file to update ECS Vars
> Updating APIBaseUrl

- test/browser/features/BrowserBasedTests/HappyPath/BRP/F2FBRPFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/BRP/F2FBRPSelectPostOfficeScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/EEAIdentityCard/F2FNICardEEAFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/EEAIdentityCard/F2FNICardEEASelectPostOfficeScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/EUDrivingLicence/F2FEUDrivingLicenceFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/EUDrivingLicence/F2FEUDrivingLicenceSelectPostOfficeScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/NonUKPassport/F2FNonUKPassportFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/NonUKPassport/F2FNonUKPassportSelectPostOfficeScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/UKPassport/F2FUKPassportFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/UKPassport/F2FUKPassportSelectPostOfficeScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/UKPhotoDL/F2FUKPhotoDLFindBranchScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/UKPhotoDL/F2FUKPhotoDLSelectPostOfficeScreen.feature
- [F2F-XXXX](https://govukverify.atlassian.net/browse/F2F-XXX)
> F2F-558 Completed happy path journey for Photo IDs

- .github/workflows/pull-request-sonar.yml
- .github/workflows/sonar-analysis-on-merge.yml
- sonar-project.properties
Implement sonar scan properties and workflow to run sonar scan on the di-ipv-cri-f2f-front.
This includes the scan files, exclusions and code coverage.   
- [F2F-100](https://govukverify.atlassian.net/browse/F2F-100)
[F2F-100]: https://govukverify.atlassian.net/browse/F2F-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-100: Add Sonar scan to ipv-cri-f2f-front

- test/browser/features/BrowserBasedTests/HappyPath/EEAIdentityCard/F2FNationalIdentityCardEEAExpiryEntryScreen.feature
- test/browser/features/BrowserBasedTests/HappyPath/EEAIdentityCard/F2FNationalIdentityCardEEANoAddress.feature
- test/browser/features/BrowserBasedTests/HappyPath/EEAIdentityCard/F2FNationalIdentityCardEEASelectCountry.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/AddressCheck/F2FNationalIdentityCardEEADifferentAddress.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/BackButton/F2FNationalIdentityCardEEAAddressCheckGoBack.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FEEAIdentityCardAddressCheckInlineError.feature
- test/browser/features/BrowserBasedTests/UnhappyPath/InlineValidation/F2FEEAIdentityCardDetailsInlineError.feature
- test/browser/pages/eeaIdentityCardAddressCheck.js
- test/browser/step_definitions/F2FEEAIdentitycard.step.js
Browser tests for the EEA ID unhappy path
- [F2F-662](https://govukverify.atlassian.net/browse/F2F-662)
[F2F-662]: https://govukverify.atlassian.net/browse/F2F-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-662 - EEA ID unhappy path tests

- src/app/f2f/controllers/checkDetails.js
- [F2F-700](https://govukverify.atlassian.net/browse/F2F-700)
[F2F-700]: https://govukverify.atlassian.net/browse/F2F-700?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-700 - Fixed countryCode payload issue

- src/app/f2f/fields.js
- src/assets/scss/application.scss
- src/lib/config.js
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/f2f/landingPage.html
- src/views/f2f/photoIdSelection.html
- test/browser/pages/landingPage.js
- test/browser/pages/photoIdSelectionPage.js
Alterations to copy and spacing
- [F2F-626](https://govukverify.atlassian.net/browse/F2F-626)
[F2F-626]: https://govukverify.atlassian.net/browse/F2F-626?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-626- Copy and spacing changes

- README.md
- template.yaml
Autoscaling min, max, trigger value and cooldown periods.
To better respond to any sudden traffic peaks, following on from DCMAW experience
- [F2F-605](https://govukverify.atlassian.net/browse/F2F-605)
[F2F-605]: https://govukverify.atlassian.net/browse/F2F-605?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-605 Update scaling policies for F2F FE ECS Auto Scaling Group

- src/app/f2f/controllers/results.js
- src/locales/en/fields.yml
- test/mocks/mappings/documentSelection.json
Remove conditional reveal element for all the radio buttons
Was getting displayed as non existing
- [F2F-911](https://govukverify.atlassian.net/browse/F2F-911)
**Before**
**After**
[F2F-911]: https://govukverify.atlassian.net/browse/F2F-911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-911]: Incorrect Copy in Expired Document Screen

- test/browser/pages/relying-party.js
Update startingURL to match latest IPV stub changes
Relevant BE changes [here](https://github.com/alphagov/di-ipv-cri-f2f-api/pull/160/files)
https://govukverify.atlassian.net/browse/F2F-921
> [F2F-921] Update startingURL to match latest IPV stub changes

- .github/workflows/post-merge-push-test-container-to-build.yml
- .github/workflows/post-merge-push-test-container-to-dev.yml
- added build and dev workflow for pushing to test containers
- [F2F-932](https://govukverify.atlassian.net/browse/F2F-932)
[F2F-932]: https://govukverify.atlassian.net/browse/F2F-932?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F-932: Added workflow files for pushing tests to container

- test/browser/features/BrowserBasedTests/HappyPath/E2E/F2FEndToEnd.feature
Suspend the BE validation checks for all tests
Suspended the BE validation checks for all tests
It was discovered that the current approach for validating BE systems using the .aws SDK via automated tests has not been done on the programme previously. 
As such, there is a requirement to temporally disable the BE checks in the pipeline until a detailed design can be thought through. 
- [F2F-978](https://govukverify.atlassian.net/browse/F2F-978)
[F2F-978]: https://govukverify.atlassian.net/browse/F2F-978?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> BE Test Suspensions

- src/app.js
Added express libraries
Express default error handler was missing
- [F2F-1002](https://govukverify.atlassian.net/browse/F2F-1002)
**Before**
https://github.com/alphagov/di-ipv-cri-f2f-front/assets/26764987/7fb1f00f-7618-41e0-b830-421cf2f5fa7f
After
https://github.com/alphagov/di-ipv-cri-f2f-front/assets/26764987/5a3d8277-fadd-4a8c-8f8d-95000c9a3067
[F2F-1002]: https://govukverify.atlassian.net/browse/F2F-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [F2F-1002]: Adding express lib for handling of any errors

- src/app/f2f/steps.js
- src/lib/config.js
EEA ID routing fixed, was previously going through EU Driving Licence route erroneously 
- [F2F-1038](https://govukverify.atlassian.net/browse/F2F-1038)
[F2F-1038]: https://govukverify.atlassian.net/browse/F2F-1038?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> F2F -1038- Incorrect Routing On EEA identity Card

- src/locales/en/default.yml
- src/views/components/countrySummaryListNoExpiry.njk
- src/views/components/eeaSummaryListNoExpiry.njk
- src/views/components/euSummaryListNoExpiry.njk
Check my answers screens had incorrect links for some options
> Fixed edit routes

- test/browser/features/BrowserBasedTests/HappyPath/E2E/F2FEndToEnd.feature
- test/browser/features/BrowserBasedTests/HappyPath/LandingPage/F2FThinFileCheck.feature
- test/browser/pages/index.js
- test/browser/pages/relying-party.js
- test/browser/pages/thinFilePhotoIdSelectionPage.js
- test/browser/step_definitions/F2FLandingPage.step.js
- test/browser/step_definitions/details.js
- test/browser/support/shared_claim.json
Tests have been added to support the new thin file ID process.
This includes:
- Adding a new test to validate the thin file routing
- updating the relying party page class to update the shared claim body 
- [F2F-1043](https://govukverify.atlassian.net/browse/F2F-1043)
[F2F-1043]: https://govukverify.atlassian.net/browse/F2F-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[F2F-1043]: https://govukverify.atlassian.net/browse/F2F-1043?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Tests for the thin file precess now in place

- .github/pull_request_template.md
- Dockerfile
- README.md
- src/app.js
- src/app/f2f/controllers/abort.js
- src/app/f2f/controllers/landingPage.js
- template.yaml
Additional logging in FE code; disable node debug logs
Improve observability of the FE code
- [KIWI-1285](https://govukverify.atlassian.net/browse/KIWI-1285)
[KIWI-1285]: https://govukverify.atlassian.net/browse/KIWI-1285?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1285 Improve logging in FE container

- .github/pull_request_template.md
- Dockerfile
- README.md
- src/app.js
- src/app/f2f/controllers/abort.js
- src/app/f2f/controllers/landingPage.js
- template.yaml
Reverts alphagov/di-ipv-cri-f2f-front#215
> Revert "KIWI-1285 Improve logging in FE container"

- src/locales/cy/default.yml
- src/locales/cy/fields.yml
- src/locales/cy/pages.errors.yml
- src/locales/cy/pages.yml
- src/views/components/countrySummaryList.njk
- src/views/components/countrySummaryListNoExpiry.njk
- src/views/components/countrySummaryListThinFileNoExpiry.njk
- src/views/components/countryThinFileSummaryList.njk
- src/views/components/eeaSummaryList.njk
- src/views/components/eeaSummaryListNoExpiry.njk
- src/views/components/euSummaryList.njk
- src/views/components/euSummaryListNoExpiry.njk
- src/views/components/summaryList.njk
- src/views/components/ukDlSummaryList.njk
- src/views/components/ukPassportThinFileSummaryList.njk
Introduced Welsh Translations for all the F2F pages
https://govukverify.atlassian.net/browse/KIWI-985
> [KIWI-985] - F2F Welsh Translation

- package.json
- test/browser/features/BrowserBasedTests/Staging/StagingEndToEnd.feature
- test/browser/pages/index.js
- test/browser/pages/orchestratorStub.js
- test/browser/step_definitions/F2FBackendValidation.step.js
- test/browser/step_definitions/orchestratorStub.step.js
- test/browser/support/AlexandraElegba.json
- test/browser/support/KennethDecerquiera.json
Add Staging Tests to F2F Front End Repo 
Support Removal of Red Button 
- [F2F-1198](https://govukverify.atlassian.net/browse/F2F-1198)
> Add Staging Tests to F2F FE Repo

- src/app/f2f/controllers/abort.js
- src/app/f2f/steps.js
Remove callback() after success abort
Build - Before Fix
Dev - After Fix
Notice we no longer get the server_error above
> [KIWI-1296] - Remove callback step after abort

- .github/workflows/post-merge-actions-build.yml
- .github/workflows/post-merge-actions-dev.yml
- .github/workflows/pull-request-sonar.yml
- .secrets.baseline
- Dockerfile
- template.yaml
Enable ECS metrics in Dynatrace
Monitor the reliability, availability and performance of AWS ECS in Dynatrace
- [KIWI-1489](https://govukverify.atlassian.net/browse/KIWI-XXXX)
[KIWI-1489]: https://govukverify.atlassian.net/browse/KIWI-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1489] Enable ECS metrics in Dynatrace

- package.json
- src/app.js
- src/lib/helmet.js
- yarn.lock
Reverts govuk-one-login/ipv-cri-f2f-front#259
> KIWI-1578: Revert "chore: Update to @govuk-one-login/di-ipv-cri-common-express"

- .github/workflows/post-merge-actions-build.yml
Fix path
Fix image pushing to build error
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> IPS-495: Fix path

- .github/workflows/post-merge-actions-build.yml
Fix bucket
Fix image being pushed to build
- [IPS-495](https://govukverify.atlassian.net/browse/IPS-495)
[IPS-495]: https://govukverify.atlassian.net/browse/IPS-495?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-495: Fix bucket

- run-tests.sh
Updating the path to /app instead of /src
Tests failing during deployment
- [KIWI-1526](https://govukverify.atlassian.net/browse/KIWI-1526)
[KIWI-1526]: https://govukverify.atlassian.net/browse/KIWI-1526?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1526]Update the path to /app instead of /src

- .github/workflows/post-merge-checks.yml
- .github/workflows/pre-merge-checks.yml
Add missing sonar stage to pre and post merge
> [KIWI-1770] Add missing sonar stage to pre and post merge

- .github/workflows/pre-merge-checks.yml
- run-tests.sh
- test/browser/features/BrowserBasedTests/HappyPath/E2E/F2FEndToEnd.feature
- test/browser/features/BrowserBasedTests/HappyPath/E2E/F2FLanguageToggle.feature
- test/browser/pages/landingPage.js
- test/browser/step_definitions/details.js
Add tests to validate Language Toggle
- [KIWI-1766](https://govukverify.atlassian.net/browse/KIWI-1766)
[KIWI-1766]: https://govukverify.atlassian.net/browse/KIWI-1766?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-1766 Language Toggle QA

- test/browser/support/F2F_CRI_AUTH_CODE_ISSUED_SCHEMA.json
- test/browser/support/F2F_CRI_END_SCHEMA.json
- test/browser/support/F2F_CRI_START_SCHEMA.json
- test/browser/support/F2F_CRI_VC_ISSUED_SCHEMA.json
- test/browser/support/F2F_YOTI_PDF_EMAILED_SCHEMA.json
- test/browser/support/F2F_YOTI_RESPONSE_RECEIVED_SCHEMA.json
- test/browser/support/F2F_YOTI_START_SCHEMA.json
remove client_id from JSON Schema following merge of KIWI-1707
- [KIWI-1707](https://govukverify.atlassian.net/browse/KIWI-1707)
[KIWI-1707]: https://govukverify.atlassian.net/browse/KIWI-1707?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update JSON Schema - remove client_id

- src/locales/cy/fields.yml
- src/locales/en/fields.yml
Removed hint from thin file doc select screen radio button
- [KIWI-1714](https://govukverify.atlassian.net/browse/KIWI-1714)
[KIWI-1714]: https://govukverify.atlassian.net/browse/KIWI-1714?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1714] - Removed hint from thin file doc select screen radio button

- test/browser/features/BrowserBasedTests/UnhappyPath/BackButton/F2FUKPhotoDLAddressCheckGoBack.feature
- test/browser/support/F2F_YOTI_START_SCHEMA.json
- test/browser/support/TestHarness.js
Remove false positives in FE TxMA Validation Tests
- [KIWI-1773](https://govukverify.atlassian.net/browse/KIWI-1773)
[KIWI-1773]: https://govukverify.atlassian.net/browse/KIWI-1773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> False positives in FE TxMA Validation Tests

- template.yaml
Turns on welsh toggle in staging
> KIWI-1782: Turns on welsh toggle in staging

- package.json
- yarn.lock
Updates the analytics package version to latest
The latest package release contains several bug fixes required by the analytics team to unblock their QA. The package has also been renamed to improve compliance.
This is the first major version push of the package, from this point forward dependabot should pick up new version releases.
[DFC-554](https://govukverify.atlassian.net/browse/DFC-554)
[DFC-554]: https://govukverify.atlassian.net/browse/DFC-554?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DFC-554: Update analytics package to v1.0.3 + change analytics package name

- src/app/f2f/steps.js
Fix for form wizard routing issues in F2F
- [KIWI-721](https://govukverify.atlassian.net/browse/KIWI-721)
https://github.com/govuk-one-login/ipv-cri-f2f-front/assets/118540036/51dea9d0-9f82-4d9a-a81c-af74a9bd6320
[KIWI-721]: https://govukverify.atlassian.net/browse/KIWI-721?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-721] - Form Wizard Crashes on Specific Expedited Routing

- yarn.lock
Upgrade Chaijs/get-func-name as it was vulnerable to ReDoS
> Upgrade Chaijs/get-func-name

- .secrets.baseline
- template.yaml
- Add new origin A record for integrating cloudFront
- Add new origin A record for integrating cloudFront
- [IPS-688](https://govukverify.atlassian.net/browse/IPS-688)
[IPS-688]: https://govukverify.atlassian.net/browse/IPS-688?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-688: Create DNS origin record for Cloufront

- package.json
- yarn.lock
Upgraded
- common-express to 6.4.0 [release notes](https://github.com/govuk-one-login/ipv-cri-common-express/releases/tag/v6.4.0)
- frontend-passthrough-headers [release notes](https://github.com/govuk-one-login/frontend-passthrough-headers/releases/tag/v1.0.0)
> KIWI-1787: upgrade packages for cf work

- .pre-commit-config.yaml
- .secrets.baseline
- template.yaml
Fix ANALYTICS_DOMAIN value in template.yaml
> [KIWI-1852] - Fix ANALYTICS_DOMAIN value

- .secrets.baseline
- template.yaml
- Deployed the cloudfront stacks on the dev
- Change DNS pointing to Cloudfront
- Change DNS pointing to Cloudfront
- Change DNS pointing to Cloudfront
- [IPS-731](https://govukverify.atlassian.net/browse/IPS-731)
[IPS-731]: https://govukverify.atlassian.net/browse/IPS-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-731: Change DNS point to Cloudfront

- template.yaml
- Due to changing load balancer, had some complexity with the waaf association
- Moved the waf association to CFN front template.
- Added the cloudfront WAF association to the CFN template. 
- Tested the transition of DNS switchover and WAF association together to replication production instance.
- Load balancer name changes when update the stack due to which the waf association become complex
- [IPS-735](https://govukverify.atlassian.net/browse/IPS-735)
Revert back to previous settings DNS and WAF Association:
Test failed as expected due to non availability of CF Headers
DNS switchover and new CF WAF Association:
All passed with the new configuration:
[IPS-735]: https://govukverify.atlassian.net/browse/IPS-735?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViL …
> IPS-731: Add CF WAF association on the Frontend CFN Template

- template.yaml
Turns on language toggle in prod
> DCP-3468: Turns on language toggle in prod

- .secrets.baseline
- template.yaml
- Deploy the cloudfront stacks on Staging and integration
- DNS switchover and WAF association
- Enable DNS switchover and WAF association
- DNS switchover and WAF association on staging and integration
- [IPS-731](https://govukverify.atlassian.net/browse/IPS-731)
[IPS-731]: https://govukverify.atlassian.net/browse/IPS-731?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-731: DNS switchover and WAF association on Staging and Integration

- .secrets.baseline
- template.yaml
- Prepration for CloudFront Go Line
- Deploy CloudFront stacks
- DNS switchover to the CF domain name
- Disable block WAF association
- DNS switchover to the CF domain name
- Disable block WAF association
- In order for go live
- Deploy CloudFront stacks
- [IPS-785](https://govukverify.atlassian.net/browse/IPS-785)
[IPS-785]: https://govukverify.atlassian.net/browse/IPS-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-785: Deploy CloudFront on F2F production environment

- .github/workflows/post-merge-actions-build.yml
- .github/workflows/post-merge-actions-dev.yml
- Update upload action ECR version from v1.2.1 to v1.2.4
- Update upload action ECR version from v1.2.1 to v1.2.4
- [IPS-816](https://govukverify.atlassian.net/browse/IPS-816)
[IPS-816]: https://govukverify.atlassian.net/browse/IPS-816?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-816: Update upload action ECR version

- .secrets.baseline
- template.yaml
Remove dependency between IPV Stub and FE stack
> Remove dependency between IPV Stub and FE stack

- .github/workflows/post-merge-actions-dev.yml
- .secrets.baseline
- dev.Dockerfile
- template.yaml
- created dev dockerfile with arm64
- updated template ECS resources
- - updated workflows `post-merge-to-dev.yml`
- Migrate All Orange Dev Stubs and Front ends to ARM64 and spot Instances
- [IPS-227](https://govukverify.atlassian.net/browse/IPS-227)
[IPS-228]: https://govukverify.atlassian.net/browse/IPS-228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-227]: https://govukverify.atlassian.net/browse/IPS-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-228 - migrate frontend to ARM

- src/app/f2f/controllers/abort.js
- src/app/f2f/controllers/abort.test.js
- src/app/f2f/controllers/checkDetails.js
- src/app/f2f/controllers/checkDetails.test.js
- src/app/f2f/controllers/landingPage.js
- src/app/f2f/controllers/landingPage.test.js
- yarn.lock
Wrap all FE to BE axios calls with check for sessionID so if one is not present user is taken immediately to error page rather than an axios call being made and resulting in error
> [KIWI-1917] Wrap BE Calls with check for govukSessionID

- .secrets.baseline
- template.yaml
- Enable block WAF and associate with the load balancer
- Disable the count WAF which was deployed with the CloudFront
- Enable the block WAF 
- Associate the block with Load balancer
- Count WAF been added during CloudFront deployment.
- Having found CloudFront working, the count waf need to be disabled to enable the block WAF
- Disable the count association with Load balancer and enable the block waf association with load balancer
- Verify the CloudFront traffic using count WAF
- [IPS-740](https://govukverify.atlassian.net/browse/IPS-740)
[IPS-740]: https://govukverify.atlassian.net/browse/IPS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-740: Enable block WAF association with Load balancer

- template.yaml
-  Add EnableSpotArmInstance  to fix the deployment issues
-  Add EnableSpotArmInstance  to fix the deployment issues
-  Add EnableSpotArmInstance  to fix the deployment issues
- [IPS-740](https://govukverify.atlassian.net/browse/IPS-740)
[IPS-740]: https://govukverify.atlassian.net/browse/IPS-740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> IPS-740: Fix the Enable Spot Arm Instance to deploy block waf

- src/app/f2f/fields.js
- src/app/f2f/steps.js
- src/assets/scss/application.scss
- src/lib/config.js
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/f2f/post-office-customer-letter-find-address.html
New screen to capture user's address search
Enables users to find the address they want their PCL to be sent to
- [KIWI-1885](https://govukverify.atlassian.net/browse/KIWI-1885)
[KIWI-1885]: https://govukverify.atlassian.net/browse/KIWI-1885?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1885]- F2F | PCL | FE | Create new Screen for Find an Address

- package.json
- src/app/f2f/controllers/checkAddress.js
- src/app/f2f/controllers/checkAddress.test.js
- src/app/f2f/controllers/root.js
- src/app/f2f/fields.js
- src/app/f2f/steps.js
- src/assets/scss/application.scss
- src/lib/config.js
- src/locales/en/fields.yml
- src/locales/en/pages.yml
- src/views/f2f/post-office-customer-letter-check-address.html
- yarn.lock
New check address screen added which uses address from shared claims and asks user if they want to use it or a different address for their PCL
Accommodate new PCL functionality
- [KIWI-1897](https://govukverify.atlassian.net/browse/KIWI-1897)
[KIWI-1897]: https://govukverify.atlassian.net/browse/KIWI-1897?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1897]- F2F | PCL | FE | Create new Check your Address screen

- package.json
- yarn.lock
Updated required packages to address security vulnerabilities
- [KIWI-1952](https://govukverify.atlassian.net/browse/KIWI-1952)
[KIWI-1952]: https://govukverify.atlassian.net/browse/KIWI-1952?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1952] - Address dependabot vulnerabilities relating to babel/traverse and protobuf

- .github/workflows/pre-merge-checks.yml
- sonar-project.properties
Updated to report to correct Sonar instance
In oder to send reports to the correct place for analysis
- [KIWI-1958](https://govukverify.atlassian.net/browse/KIWI-1958)
[KIWI-1958]: https://govukverify.atlassian.net/browse/KIWI-1958?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-1958] - | Platform | Change to new OL Sonar Organisation

- .github/workflows/pre-merge-checks.yml
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> Reinstated sonar checks

- package.json
- yarn.lock
> Update govuk-frontend from v4.8.0 to v4.9.0.

- package.json
- yarn.lock
This reverts commit 7e8753b7e32c461dafaa39a57300571796f69bd6.
> Revert "update govuk-frontend from v4.8.0 to v4.9.0. (#542)"

- src/locales/en/fields.yml
Corrected typos in PCL screen text
- [KIWI-2104](https://govukverify.atlassian.net/browse/KIWI-2104)
[KIWI-2104]: https://govukverify.atlassian.net/browse/KIWI-2104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2104] - F2F | PCL | FE | Screen Updates to Align with Figma Designs

- src/assets/scss/application.scss
- src/locales/cy/pages.yml
- src/locales/en/default.yml
- src/locales/en/pages.yml
- src/views/f2f/choose-post-office-prove-identity.html
- src/views/f2f/post-office-customer-letter-choose-address.html
[KIWI-2131] Update Front End Screens with Customer Letter details
[KIWI-2131]: https://govukverify.atlassian.net/browse/KIWI-2131?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2131] Update Front End Screens with Customer Letter details

- src/app/f2f/controllers/checkDetails.js
Removed hardcoded payload value for PCL, this value is now assigned based on user input
To enable users to select printed letter choice
> [KIWI-XXXX] - Remove hardcoded payload value for PCL

- src/locales/cy/pages.yml
- src/locales/en/pages.yml
- test/browser/features/BrowserBasedTests/UnhappyPath/CMAChangeButton/F2FCheckAnswersPOLocationChange.feature
- test/browser/pages/landingPage.js
- test/browser/step_definitions/details.js
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> [KIWI-2156] Removing references to 15 days on F2F landing page

- dev.Dockerfile
Updated dev docker file to node 20
Updated dev docker file to node 20
To allow local testing with docker and to align with version update of node across f2f
> KIWI-2069: Updated Docker dev file node version which was missed in initial PR

- src/locales/cy/pages.yml
- src/locales/en/pages.yml
`[KIWI-2157] Update F2F Screens with Customer Letter details`
- KIWI-2157
<table>
<tr>
<th>Before</th>
<th>After English</th>
<th>After Welsh</th>
</tr>
<tr>
<td><img width="400" src="https://github.com/user-attachments/assets/03cc84b8-1819-47dc-aa55-ad5e39d79a13" /></td>
<td><img width="600" alt="Screenshot 2025-02-12 at 10 07 02" src="https://github.com/user-attachments/assets/82e07cc8-a57e-4c09-a755-67b01f4c9093" /></td>
<td><img width="600" alt="Screenshot 2025-02-12 at 10 07 22" src="https://github.com/user-attachments/assets/16559a61-280c-4767-a9a2-fe48e7d4234e" /></td>
</tr>
</table>
[KIWI-2157]: https://govukverify.atlassian.net/browse/KIWI-2157?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2157] Update F2F Screens with Customer Letter details

- src/locales/cy/pages.yml
- src/locales/en/pages.yml
Reverts govuk-one-login/ipv-cri-f2f-front#586
> Revert "[KIWI-2157] Update F2F Screens with Customer Letter details"

- .github/workflows/post-merge-checks.yml
- .github/workflows/pre-merge-checks.yml
- .gitignore
- eslint.config.mjs
- src/app.js
- src/app/f2f/controllers/landingPage.js
- src/app/f2f/controllers/root.js
- src/app/f2f/featureSets.js
- src/app/f2f/featureSets.test.js
Added feature set functionality to allow session based toggling
To allow PCL screens to be toggled on and accessed without enabling the full journey
> KIWI-feature-set: Added feature set functionality to F2F for PCL

- package.json
- src/app.js
- template.yaml
Added FE Vital Signs logging to track values that inform Capacity Management work
> KIWI-2011 - Implementing FE Vital Signs Logging

- src/app/f2f/controllers/checkDetails.js
- [KIWI-XXXX](https://govukverify.atlassian.net/browse/KIWI-XXXX)
> Update address payloads

- Dockerfile
- template.yaml
- Configured AWS ECS healthchecks in template
- Updated Dockerfile to reference healthcheck
> KIWI-2017 - Configuring ECS Healthchecks

- dev.Dockerfile
Added Health check to dev.dockerfile to make inline with other environments
> KIWI-2017 - Updating dev.dockerfile to match other environments

- run-tests.sh
- test/browser/pages/relying-party.js
Updates to stub URL following update to IPV_STUB_URL GitHub secrets in Kiwi owned CRI's
- [KIWI-2302](https://govukverify.atlassian.net/browse/KIWI-2302)
[KIWI-2303]: https://govukverify.atlassian.net/browse/KIWI-2303?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[KIWI-2302]: https://govukverify.atlassian.net/browse/KIWI-2302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> KIWI-2302: Updates to stub URL

- package.json
- yarn.lock
form-data v4.0.0 -> 4.0.4
To address critical axios vulnerability 
- [KIWI-2412](https://govukverify.atlassian.net/browse/KIWI-2412)
[KIWI-2412]: https://govukverify.atlassian.net/browse/KIWI-2412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [KIWI-2412] - Address critical vulnerability in transitive dependency form-data
